// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace TimeAndLapseLibrary.Data.Designer
{
    // Timings
    public partial class TimingConfiguration : EntityTypeConfiguration<Timing>
    {
        public TimingConfiguration()
            : this("dbo")
        {
        }
 
        public TimingConfiguration(string schema)
        {
            ToTable(schema + ".Timings");
            HasKey(x => x.TimingId);

            Property(x => x.TimingId).HasColumnName("TimingID").IsRequired().HasColumnType("uniqueidentifier").HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
            Property(x => x.Time).HasColumnName("Time").IsRequired().HasColumnType("datetime");
            Property(x => x.RunId).HasColumnName("RunID").IsRequired().HasColumnType("uniqueidentifier");
            Property(x => x.TimingTypeId).HasColumnName("TimingTypeID").IsRequired().HasColumnType("uniqueidentifier");

            // Foreign keys
            HasRequired(a => a.Run).WithMany(b => b.Timings).HasForeignKey(c => c.RunId); // FK__Timings__RunID__35BCFE0A
            HasRequired(a => a.TimingType).WithMany(b => b.Timings).HasForeignKey(c => c.TimingTypeId); // FK__Timings__TimingT__36B12243
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
