use TimeAndLapse
go

--DROP CHIAVI ESTERNE	

ALTER TABLE Timings DROP CONSTRAINT FK__Timings__TimingT__36B12243
GO
ALTER TABLE Timings DROP CONSTRAINT FK__Timings__RunID__35BCFE0A
GO


ALTER TABLE Runs DROP CONSTRAINT FK__Runs__MancheID__3D5E1FD2
GO


ALTER TABLE Manches DROP CONSTRAINT FK__Manches__PlayerI__3A81B327
GO
ALTER TABLE Manches DROP CONSTRAINT FK__Manches__RoundID__3B75D760
GO
ALTER TABLE Manches DROP CONSTRAINT FK__Manches__Tournam__3C69FB99
GO


ALTER TABLE Players DROP CONSTRAINT FK__Players__CrewID__30F848ED
GO
ALTER TABLE Players DROP CONSTRAINT FK__Players__EventID__31EC6D26
GO
ALTER TABLE Players DROP CONSTRAINT FK__Players__Registr__2F10007B
GO
ALTER TABLE Players DROP CONSTRAINT FK__Players__TeamID__300424B4
GO


ALTER TABLE Registrations DROP CONSTRAINT FK__Registrat__Parte__2D27B809
GO
ALTER TABLE Registrations DROP CONSTRAINT FK__Registrat__RaceI__2E1BDC42
GO


ALTER TABLE Events DROP CONSTRAINT FK__Events__Category__33D4B598
GO
ALTER TABLE Events DROP CONSTRAINT FK__Events__Champion__34C8D9D1
GO
ALTER TABLE Events DROP CONSTRAINT FK__Events__RaceID__32E0915F
GO


ALTER TABLE Scores DROP CONSTRAINT FK__Scores__Champion__398D8EEE
GO
ALTER TABLE Scores DROP CONSTRAINT FK__Scores__PointID__37A5467C
GO
ALTER TABLE Scores DROP CONSTRAINT FK__Scores__SeasonID__38996AB5
GO


-- DROP TABELLE


DROP TABLE TimingTypes
GO

DROP TABLE Points
GO

DROP TABLE Seasons
GO

DROP TABLE Categories
GO

DROP TABLE Partecipants
GO

DROP TABLE Rounds
GO

DROP TABLE Timings
GO

DROP TABLE Runs
GO

DROP TABLE Manches
GO

DROP TABLE Teams
GO

DROP TABLE Scores
GO

DROP TABLE Registrations
GO

DROP TABLE Races
GO

DROP TABLE Players
GO

DROP TABLE Events
GO

DROP TABLE Championships
GO

--DROP DATABASE
USE master
Go
DROP DATABASE TimeAndLapse
GO